[config]
schemaVersion = "0.0.1"

[package]
namespace = "XoXFaby"
name = "MoreItems"
versionNumber = "2.1.5"
description = Cracked Orb Rework! Extra items intended to fit into the style and balance of the vanilla gameplay."
websiteUrl = "https://github.com/xoxfaby/MoreItems"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.4.9"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "../zip"

[[build.copy]]
source = "../bin/Release/netstandard2.0/MoreItems.dll"
target = "MoreItems.dll"


[publish]
repository = "https://thunderstore.io"
communities = ["riskofrain2"]
categories = ["mods", "items"]